### ISSUE TITLE
Broken link on Advanced WiFi page

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#106]
On the "Advanced Wifi" page here - http://box.local:1880/wifi - the link to "basic WiFi setup" link goes to box.local (which doesn't exist).

![image](https://user-images.githubusercontent.com/354542/51257170-f0fab480-199e-11e9-9b1c-8190751c6fff.png)

That whole sentence:

> If you do not have a username and password or a hidden network for your WiFi, then use the basic WiFi setup page instead.

... is a bit odd...

Perhaps we could rephrase to say:

"If you're on a simple WiFi network, please try configuring WiFi on your Box using the WiFi card instead."

**Comment by amcewen** [comment]
If you're configuring your box using the wifi card then http://box.local *will* exist as that's where the simple WiFi config will live.

Happy to tweak the wording on the page though.

**Comment by george08** [comment]
Ah, ok. Yes, do please tweak the wording so it's a bit clearer... Ta.

**Comment by amcewen** [comment]
Have changed it to "Enter the details for your WiFi network below. If you're on a simple WiFi network, then use the basic WiFi setup page" (where *basic WiFi setup page* is a link to the other setup page)
