### ISSUE TITLE
Audio feedback when box is restarting after an update

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#110]
It's great that the Upgrade cards are now working!

It is a bit of a surprise that the Box silently restarts, and then Gill says "OK, ready to go!" again, without you doing anything.

This seems like a perfect time to a) add a bit to the script that says "I'll just restart myself now. Be right back." AND/OR #89.

**Comment by george08** [comment]
And, would be extra nice if the blinky lights blinked when the Box is updating.

**Comment by amcewen** [comment]
We need some new audio files:
 * One to tell the user we're going to restart
 * One to tell the user we're not on the wifi, and to check that first
 * One to tell the user we've found an update and we're about to update the box
 * Split the "checking" for updates file so it first checks for new audio content, and then "now checking to see if there are any software updates"

**Comment by george08** [comment]
Have added updates to https://github.com/museuminabox/brain/wiki/Box-Audio-Scripts

**Comment by george08** [comment]
Audio has been recorded and sent to AMc.
