### ISSUE TITLE
Add a way to forget all of the wifi details

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#115]
If you accidentally get a set of WiFi credentials configured that don't work (maybe there's a captive portal, for example), then there's no way to tell the box to *forget* those details when you try to tell it the correct credentials.

Maybe the WiFi config page could have a "forget all the networks I know about" link to let you reset it if you're having problems...

**Comment by george08** [comment]
1. Show list of all wifi networks the Box knows about; can we also show network names that we couldn't connect to?
1. Add link to "forget" one, or all of them
1. Add link from "main wifi details page" to Advanced Wifi config

**Comment by amcewen** [comment]
Moved to new repo
