### ISSUE TITLE
WiFi setup script should report captive portals

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#119]
When the configure-wifi script finishes and tests whether it can connect to the Internet, it should be able to spot the difference between couldn't connect at all and got a response but not the page we expected, and work out if that's likely to be a captive portal.

We should report the difference to the user.

**Comment by george08** [comment]
"Hmm. I'm trying to connect to that network, but it's asking me for more details, like an extra setting, but we can't provide that."

(or something)

**Comment by amcewen** [comment]
Got the test page online, and the code written to fetch it and check its contents.  Currently it's only wired into the "check for updates" flow (that's easier to test the different scenarios first as it doesn't involve dropping off the WiFi).

At the moment it reports errors just as a string - next step is to implement custom error classes (e.g. in https://medium.com/@xjamundx/custom-javascript-errors-in-es6-aa891b173f87) so I can then handle them correctly.  Then add it to the WiFi config flow too.

**Comment by george08** [comment]
Cool!

**Comment by amcewen** [comment]
I've extended the check-for-upgrades and the configure-wifi flows so they (try to) detect any captive portals, and also provide better feedback for WiFi problems.

We'll need three new audio clips please @CharlieMiab, and maybe updates for some of the existing ones.  At present the same error clips get used for both the update and the configure-wifi flows, but they can be different if need be.

The flows now are as follows:

### Configure WiFi
 * Plays `configure-wifi.wav`
 * Runs the WiFi config script, which creates the MuseumInABox WiFi hotspot and provides the web GUI to configure your WiFi network
 * When the user has entered their WiFi details, or if they leave it 2 minutes without doing anything...
 * Play the **new** `check-the-wifi.wav` which let's the user know it's checking to see if things worked
 * There'll be a ~10 second pause while it waits for the WiFi to connect and then checks to see if we're online
 * if...
   * ...it worked, it'll play `wifi-works.wav`
   * ...it failed and it looks like we're behind a captive portal, it'll play the **new** `captive-portal.wav`.  We won't be able to work round that, so try a different WiFi network.
   * ...it failed and we've got an IP address but didn't get a web page, it'll play the **new** `wifi-but-no-internet.wav`  So connecting to the WiFi worked, but we can't get from that WiFi network out to the Internet for some reason.  Check if there's a problem with that network's connection to the Internet, or try a different WiFi network.
   * ...it failed and we don't seem to be connected to WiFi, it'll play `wifi-failed.wav`.  Either try again or try a different WiFi network.

### Check for upgrades
 * Plays `checking-for-content.wav`
 * Checks to see if we're online. If...
   * ...it worked, it then syncs any content, then plays `collections-updated.wav` and the rest as usual
   * ...it failed and it looks like we're behind a captive portal, it'll play the **new** `captive-portal.wav`.  We won't be able to work round that, so try a different WiFi network.
   * ...it failed and we've got an IP address but didn't get a web page, it'll play the **new** `wifi-but-no-internet.wav`  So connecting to the WiFi worked, but we can't get from that WiFi network out to the Internet for some reason.  Check if there's a problem with that network's connection to the Internet, or try a different WiFi network.
   * ...it failed and we don't seem to be connected to WiFi, it'll play `wifi-failed.wav`.  Either try again or try a different WiFi network.

**Comment by george08** [comment]
Related (usability issue): https://github.com/museuminabox/brain-dei-mille/issues/25

**Comment by amcewen** [comment]
For reference, when an Android phone encounters a captive portal it pops up a notification saying "Sign in to WiFi network required", so maybe we could say something like "this WiFi network needs extra sign in steps that we can't complete"?

**Comment by amcewen** [comment]
This is all done now.  If it encounters a captive portal it now forgets that network, so it'll be less likely that someone will accidentally join a captive portal network and then get trapped there.

**Comment by CharlieMiab** [comment]
_Adding the testing I did for the captive portal test .img for reference_

In the Royal Armouries Museum: 

1. Turned the Box on and Booped the WiFi Card
2. Using my iPhone, selected the MuseuminaBox WiFi network and the pop-up appeared. 
3. Chose the 'Royal Armouries Free WiFi' network, left the password field blank and submitted.
4. Heard the robot-brummie saying 'Give me a second to check if that worked', waited a few seconds, then heard 'I may be behind a captive portal'. 

Repeated this process three times, turning the Box off after each try and experienced the same flow as listed above.

![ra_wifi_testing](https://user-images.githubusercontent.com/22318401/76979105-6f4e4000-692f-11ea-8acd-793cc5faeaf1.JPG)
