### ISSUE TITLE
Introduce a "Admin Objects" collection + register Admin Object boops

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#121]
We're planning to send 6 "admin objects" with our new Make Your Own kits:

1. Hello card
1. WiFi card
1. Upgrade card
1. Content card 1: God from the Sea
1. Content card 2: TBD
1. Content card 3: TBD

These are intended to help users get their Box set up, and to show them three examples of great content, which they can try to emulate in the MYO experience.

We could also use this Admin collection on Heart to help users configure their Box optimally. See https://github.com/museuminabox/museuminabox-v2/issues/212. This would be a good helper to reinforce to people that they can use their Admin Objects collection!

We also need the Admin Objects to register boops, both so the User can see that it's registered, and Admins at HQ can see that the User has tried to use them.

**Comment by george08** [comment]
- Have to think who can see Admin Object boops (and where)... maybe only Box owners and Staff.
- Can add an icon to easily ID, e.g. https://thenounproject.com/search/?q=wrench&i=2939569 (CC-BY)

**Comment by george08** [comment]
https://github.com/museuminabox/museuminabox-v2/issues/212

**Comment by george08** [comment]
Here is the Content Cards collection:
https://heart.museuminabox.org/view_collection/345

**Comment by amcewen** [comment]
Admin objects are in https://heart.museuminabox.org/view_collection/104

We'll have a "default box" in `heart` which has the "admin" and "Try me" collections added - then the ansible script can pull down the list of audio files that need to be pre-loaded in an image.

In the very-short-term (until this and the [corresponding issue on heart](https://github.com/museuminabox/museuminabox-v2/issues/217) are fixed) we can manually add those collections to any boxes we need to ship out.

**Comment by george08** [comment]
I've retired the old Admin collection (104), and made a fresh one: https://heart.museuminabox.org/view_collection/378

**Comment by amcewen** [comment]
Admin objects and Try Me collections now added, and admin object boops show up in the boop log too.

**Comment by george08** [comment]
Cool - and the Try Me objects appear as public boops too?

**Comment by amcewen** [comment]
![image](https://user-images.githubusercontent.com/108468/70447118-249e6b80-1a96-11ea-9d84-38d04b95a2da.png)

Yep.

**Comment by george08** [comment]
SUPER SWEET.
