### ISSUE TITLE
Instantiate Box in the DB when they are built

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#122]
Migrated from https://github.com/museuminabox/brain-dei-mille/issues/17:

@george08:
> It would be super helpful and much quicker if a Box could register itself somehow when it's booted up at HQ...
>
> I'm imagining it would get a new entry here: https://heart.museuminabox.org/backstage/boxes/box/
>
> And it would be absolutely amazing if it said its new hardware ID number out loud, which we could write on the bottom of the Box. OMG that would be amazing.

> We've been thinking through production process/timing etc and thinking that configuring boxes is quite time-consuming.

> @Rjevski and I had a quick chat about this at HQ. Lots of options...

**Comment by amcewen** [comment]
We'd need a way to cope with "box upgrades" too, so we don't generate unnecessary boxes in the database each time we write an image to replace an SD card in a box (i.e. cases where we'd currently visit `box.local:1880/upgrade`)

**Comment by Rjevski** [comment]
For box upgrades it becomes a bit difficult - if the upgrade is online we can have two partitions on the card (one data partition and one system partition, like Android and OpenWrt devices) and the upgrade only overwrites the system one.

If it’s a physical SD card replacement then it becomes more difficult.

Maybe we can just use an existing hardware ID like the MAC address?

Sent from my iPhone

On 30 Oct 2019, at 16:08, Adrian McEwen <notifications@github.com> wrote:

﻿

We'd need a way to cope with "box upgrades" too, so we don't generate unnecessary boxes in the database each time we write an image to replace an SD card in a box (i.e. cases where we'd currently visit box.local:1880/upgrade)

**Comment by Rjevski** [comment]
I've updated the issue to reflect that we've decided to instantiate boxes manually when we build them (and get the config file on the SD card).

**Comment by Rjevski** [comment]
For speaking its hardware ID out loud we could use an online text-to-speech API and generate a file the box can download and play on every boot.
