### ISSUE TITLE
Tell a Box there’s a Collection coming

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#124]
Imagine if someone orders an MYO kit, which we send, and then they come back and order a Collection… 

Also, what if their Box isn’t online?

**Comment by amcewen** [comment]
Then within half an hour their box would have downloaded all that content automatically.
And if their box isn't online, it would download it when it's next booted up somewhere it can get online.
And if they went to `/prints` before the content had automatically downloaded, they'd still get shown the new collection (the box checks with `heart` when it builds the `/prints` page), and the download of the audio is kicked off in the background at the same time too.

What are you thinking the box would do if it knew there's a collection coming?

**Comment by george08** [comment]
Mostly download the collection pre-emptively, so you can take it out of the envelope when you receive it and have it just work.

(So yes, we'd ideally pre-configure the stickers here, too. Although, perhaps that would be fun or desirable for people with MYO kits, but maybe only if they've successfully written a sticker themselves already.)

**Comment by george08** [comment]
If Box has never been on WiFi, it would also be good for there to be some kind of response from the Box like "I don't recognise that object or sticker. Has your Box been on a WiFi network yet? Perhaps you could set that up, then I can check for any new Collections." etc

**Comment by george08** [comment]
Related: #81
