### ISSUE TITLE
Make boxes fetch their config from the boot partition

### ISSUE THREAD

**Issue by Rjevski** [museuminabox/brain#126]
We no longer want the boxes to register themselves on first boot like they currently do.

Instead, the boxes should expect a unique configuration file in their boot partition and use that as their identity (UUID, etc). If the file is missing the box should refuse to start and speak out an error message.

**Comment by amcewen** [comment]
@Rjevski made a couple of commits towards this:
 * https://github.com/museuminabox/brain/commit/aac3ac145c70c9a69acad2313bf52e898b254d63
 * https://github.com/museuminabox/brain/commit/172a6786cbeff1e642e77aab9dca6f321032cd14

The NodeRED flow needs to load the config from the new location, and needs to not play the "OK, ready to go" audio if the config file isn't there.  I'm thinking it might be better to move the "this box isn't configured" warning audio to that check too, so the check only happens in one place.

We also need to record a final version of the "box not configured" audio - it _shouldn't_ ever happen to a box out in the wild, but we should have user-friendly message just in case.

**Comment by amcewen** [comment]
Have made most of those changes - still needs better audio, and will upload a test `img` for you to test the `heart` side of saving the config to SD card

**Comment by Rjevski** [comment]
Thanks! Does this prevent the box from starting if the config is missing? Because what I observed previously is that it would still work and read objects even if the config failed to load.

Part of me actually wants the check to be done as a systemd dependency to Node Red so the app doesn't even start if the config is missing.

**Comment by amcewen** [comment]
No, it doesn't prevent the box from starting if the config is missing, because the box should gracefully degrade its functionality - if the config file somehow gets corrupted/deleted out in the field the user will get the warning when it first boots up but any content already on the box will still work.

**Comment by amcewen** [comment]
New, friendlier audio added.  So this is now all done.
