### ISSUE TITLE
Make the Update card check for new audio too

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#128]
We're in a customer support loop with the Ure Museum at the moment, because they've asked us to update several of the audio tracks they supplied initially. We're happy to update the audio, and have done, but, it sounds from their emails like the new audio has not yet downloaded to the Box.

> Apologies, but the updates don’t seem to have worked. Claudina tried it at her home and failed; 
> Amara tried it at her home and failed; Claudina tried it at the Uni and failed; now I’ve tried it at 
> my home, and failed.
>
> Am I doing something wrong?
> I connect to the web; when I’m connected…
> I put the update card on; when he says ‘all is updated’…
> I put a postcard or artefact on and should hear the difference, but I don’t.
> 
> Please let me know if I’m doing something wrong and, if not, what to do…
 
Just noting here that she assumed the Update card updates content (and not the brain software particularly). I think would be better than what we have now - if it could check for both types of updates (content and software).

In the meantime, I guess I'll have to direct them to box.local:1880/prints and have them click the "Check for new audio" button? 

Is there anything you'd like me to ask or do to try to help work out why the audio update has apparently not worked?

**Comment by amcewen** [comment]
We should (at least to try) not do the automatic updates in the background when we add this, so there's two ways content can be updated: by using the updates card, or clicking on the button in `/prints`.

We should (at least to try out) play the "checking for new content" audio when the button is clicked in `/prints` too.

**Comment by amcewen** [comment]
New improved flow and better audio added; the updates card now checks for new content before checking for new software; and we no longer automatically check for new content in the background.
