### ISSUE TITLE
What happens when the Brain encounters an object it doesn't know about?

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#13]
When you place an object onto a box and it doesn't know what it is, how does it deal with that?

**Comment by george08** [comment]
(Gill)
"Hmm. I'm not sure what this thing is." 

Tricky part with our error handling & scripts is that we'll probably need things to be yes/no answers, or to direct people online...

**Comment by george08** [comment]
Nice to have - future enhancement. Can't wait until we can really spend some time refining and making the simple Box really robust!
