### ISSUE TITLE
Send note to Heart when Box successfully connects to WiFi remotely

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#131]
Since this is the first and crucial step in Boxes living in the wild, it would be very useful to have clear and obvious reporting on either /backstage/box/ or heart/box (for staff, too) that a Box has connected to WiFi.

For V1, I'm imagining a note somewhere on both of those views that says "This Box connected to WiFi remotely on YYYY.MM.DD."

**Comment by amcewen** [comment]
Migrated to new repo.
