### ISSUE TITLE
Make it easier to provision a new brain

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#17]
In concert with the work in issue #10, we'd like an easier way to bootstrap a brain.

The workflow will be as follows:
- Once the brain software is installed, visit http://brain-ip-address:1880/setup
  - That pulls a list of boxes from museuminabox.org
  - Shows the list of boxes for you to choose from.
- When the box is selected, it will save the relevant config for the brain (hostname, config in Node-RED so that Boops are correctly recorded, etc.)
- The initial syncing of content (unless issue #10 renders a specific initial sync unnecessary) should be kicked off
- Then you'll be redirected to http://brain-ip-address:1880/prints
  - That will show a list of prints, with a "write tag" button next to each one.
  - Clicking the "write tag" button will write the relevant info to the NFC tag

**Comment by george08** [comment]
I find myself wanting this more and more @amcewen. I've had a good few days (finally) to work on content stuff. Not just for The First Commission, but wanting to whip up things quickly, like The World's Smallest Hans Sloane Collection. :)

Do you think we could try to organise a day or two to concentrate on this one?

**Comment by amcewen** [comment]
From the merge comment of branch "Feature/17 easier provisioning":

In lieu of knowing how to better streamline the whole provisioning a box process (writing tags, etc.), this fixes issue #17 (and we can open more specific bugs once/if we have a better process in mind).
