### ISSUE TITLE
Reduce the lag between presenting a tag and hearing sound

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#20]
There's an ~3 second gap between you presenting an object and having audio come out of the speakers.  This is mostly the time taken to read the tag, and needs to be as quick as possible.

Things to investigate:
- Parsing the NDEF data as we go and stopping as soon as we've read it all (it currently reads in the whole tag, and then parses it for NDEF data
- Rewriting the RFID reading and NDEF parsing code in C/C++
- Trying the different NFC reader that I've got, in case that's faster (would also be using libnfc, which is more generalised for future expansion/compatibility, and more of it is written in C++ already)
- Something else we've not thought of yet...

**Comment by george08** [comment]
I'd call this more a essential need than an enhancement. The current delay is confusing to people when we show it to them. The first instinct is 'oh, this isn't working, i'll take it off' and that's just when the playing starts, and then you get this jerky thing. Ideally, this interaction would be as close to instant as we can get it, as you say.

**Comment by amcewen** [comment]
The commits https://github.com/museuminabox/brain/commit/01a1ac044c24c39f1d568b86c270b40b60583300 and https://github.com/museuminabox/brain/commit/8dc74b3595eda0c12a7e9d801469db1d0e8a33a9 made this much better.
