### ISSUE TITLE
Filenames with special characters

### ISSUE THREAD

**Issue by nebulousflynn** [museuminabox/brain#22]
Just a note to say that there are some inconsitencies between S3 file names and the URLs it serves up i.e.:

URL from S3 / written to tag:   Adam+%26+The+Ants+-+Prince+Charming.wav
File loaded onto pi:                  Adam+&+The+Ants+-+Prince+Charming

I fixed this by renaming the file via FTP to include %26 instead of &.

Brackets seem break things entirely - not necessarily an issue with code as could be fixed by naming things differently as they are uploaded to S3

**Comment by george08** [comment]
Is this still an issue?
