### ISSUE TITLE
Playback bug? Restarts without cause?

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#23]
This is a bit hard to reproduce, but, I've noticed it happening about 50% of the time. The media successfully plays (for Big BM or Tweet of the Day) and then will restart without any intervention.

**Comment by george08** [comment]
Just noticed it on our Marsh Tit card. We then played another card, then went back to Marsh Tit. Second Marsh Tit play, it went for longer than the first time it restarted, but then restarted eventually.

**Comment by amcewen** [comment]
Hmm, given this is a year old now, I'm thinking we close it until we see a more reproducible (or more regular) problem with it.
