### ISSUE TITLE
Timed LEDs take too long to light up

### ISSUE THREAD

**Issue by nebulousflynn** [museuminabox/brain#25]
the Brain start up time is so fast now (good thing) that the timed LEDs light up slower than they should i.e. the Big Green LED lights up before all the orange ones have finished turning on

**Comment by amcewen** [comment]
If you've got a box with LEDs to hand (I've not just at the moment, but will get one at some point) it'd be good to time how long it takes to (a) get to the first yellow LED and (b) to the green LED.  I'll do a couple of tests with the Pi3 and see if that's any faster too, and we can settle on the shortest time for them...
