### ISSUE TITLE
Point Brains at api.museuminabox.org

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#26]
Once we've set up the DNS (as detailed in https://github.com/museuminabox/museuminabox/issues/49) we'll need to update the flows_brain.json file to point to that rather than museuminabox.herokuapp.com (or www.museuminabox.org for older Brains).

**Comment by george08** [comment]
So... you prefer not to have api.museuminabox.org @amcewen ?

data.museuminabox.org?
boxes. ?
boops. ?

**Comment by george08** [comment]
Is this the only other host we need?

**Comment by amcewen** [comment]
api.museuminabox.org makes sense for the brains to use, but feels wrong (to me) for humans to use.  What would we call it in conversation?  At present it gets referred to as "the heroku site", so finding something better would be good for office discussions too :-D

I think data.museuminabox.org is my preference so far, but it's not very exciting.

For now I think we just need the one site.  It's too early to predict what our infrastructure will look like when we've got millions of boxes deployed and need something else :-D

**Comment by george08** [comment]
heart.museuminabox.org ?

**Comment by amcewen** [comment]
It'd end up (as currently proposed) with URLs that are heart.museuminabox.org/heart/... but that was what came to mind when I first saw those URLs.  Could we just lose the /heart/ bit of those if we move to heart.museuminabox.org?  That seems the best proposal to me.

**Comment by george08** [comment]
we just did /heart yesterday because it was faster than creating a subdomain...

**Comment by george08** [comment]
#49 is complete.
