### ISSUE TITLE
Tidy up micro:bit integration

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#30]
We need the Brain to work out what things to send to the micro:bit so that we can relay metadata over to other micro:bits.

At present it sends "y<year>" and "p<place>" packets, followed by an "f" packet, for each boop.  They should just be sent as separate lines of text to the serial port, at 115200 baud.  Once we know what metadata to send, we might need to extend things, both in the flow and in the microbit-miab code.

**Comment by george08** [comment]
This is far from a priority.
