### ISSUE TITLE
Add ability for users to record their own audio

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#31]
As an MVP we want to let users (with appropriate\* hardware) record an audio file to replace the "official" audio for any given object.
1. Connect "recording box"
2. Place object to record onto the brain, it will report "Recording in 3...2...1..." rather than the usual playback
3. Remove the object to stop recording
4. Replay your recording to check it over
5. Once happy with it, press "Save" to store it on the Brain (locally for the MVP)

The record, replay and save features might be triggered by physical buttons.

*appropriate is still to be fully defined, likely as part of resolving this issue :-)

**Comment by george08** [comment]
We're going to need this pretty soon! :)

**Comment by george08** [comment]
Could we connect a button to the USB port on Pi? Place an object on the Brain, hit the button, and it records...?

(Have also been poking at Chrome, which can present a recording UI that taps into the computer microphone... could be an option/web UI.)

**Comment by amcewen** [comment]
Here seems as good a place as any to note [this tiny USB microphone](https://www.amazon.co.uk/gp/product/B00XU1GHO4/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)

**Comment by george08** [comment]
Let's close this - for now it can be handled by uploading a .WAV via the web UI.
