### ISSUE TITLE
Problems writing / overwriting tags

### ISSUE THREAD

**Issue by nebulousflynn** [museuminabox/brain#33]
Having trouble writing tags for the I See Wonder brain - possible long audio file names?

Problems with prints IDs 176, 177, 178.

i.e. https://s3-eu-west-1.amazonaws.com/miab-brain-content/audio/i_see_wonder/astronomy/7-Schematic-of-Saturns-rings-from-Cristiani-Hugenii-Zulichemii.wav

**Comment by amcewen** [comment]
It's a size problem (as we worked out a while back).  Trying to write too much data to the tag can corrupt the tag.

I've updated the Node RED rfid nodes so they check the size of the tags (for any of the NTAG2xx classes of tags) in https://github.com/mcqn/node-red-contrib-nfc/commit/5f55bfc69dd018f389714957e469002435c658c6 which **mostly** fixes the problem.

The bit it doesn't fix is telling you that it hasn't written the tag.  You just won't get the "OK" message.  I had a look at fixing that, but couldn't find how to catch the error and pass that through :-/  The error shows up in the debug console of the Node RED screen, but not through to the Javascript showing the status next to the button.

Looking at it more now, I haven't quite done enough in the rfid nodes to communicate the error.  I'll pick it up from http://nodered.org/docs/creating-nodes/node-js#handling-errors when I'm next working on this.

**Comment by nebulousflynn** [comment]
thanks for info @amcewen - wondering if we could also limit char length for input fields in Admin to prevent this too

**Comment by amcewen** [comment]
I've worked out how to improve the error reporting through this, so it now gets passed to the `/prints` page as well as reported  in the debug console (so you see more quickly on the `/prints` page rather than having to wait for the AJAX call to time out).
