### ISSUE TITLE
Boot progress PCB improvements

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#37]
It'd be useful for the custom PCB to have some M3 mounting holes so we can mount it into the skull more easily.

**Comment by amcewen** [comment]
We should also add the logo and URL to the bottom silkscreen.  And round off the corners of the PCB.

**Comment by george08** [comment]
Can @CharlieMiab help with this? (Don't think we need it for Smithsonian phase?)

**Comment by amcewen** [comment]
These changes were done in September https://github.com/museuminabox/brain/commit/c4a0ac8ae2831fba93a58347b327d153053245c1

And we've already had a bunch of the boards fabbed (they're what we're into using now).  I'd just missed out tying the commit back to this issue.
