### ISSUE TITLE
Unpredictable/occasional restarting issues

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#39]
Sometimes the Brain will reboot while powering up, at times repeatedly.  @george08 recorded the problem with one of the Brains being demoed/used on Monday.

It seems to be power-related.  I've seen it happen if using a thin USB cable rather than one of the better-specced USB power supplies (either the 5V 2A ones I've been buying from Farnell, or the 5.1V 2.5A official Raspberry Pi supplies).  Possibly also a problem when battery packs are running low or if lower-powered phone chargers are used.

**Comment by amcewen** [comment]
When I've noticed it, it seems to happen around the time that the "one moment please" boot message is played.  I wonder if that's because it causes more power draw through the amp then?

**Comment by george08** [comment]
Each restart on Monday happened *just* before it got to the green light. It would go back to the start, with the left-most light on. I don't think it replayed the "one moment please".

**Comment by george08** [comment]
Let's close this one year old bug. Can reopen or recreate if we can reproduce.
