### ISSUE TITLE
Ditch video support on NFC tags?

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#44]
We've used NTAG213 in the past, limited to 142 bytes.
We're now using NTA216 tags, at 888 bytes each.

NTAG216 is double the cost of NTAG213, which starts to matter when we're buying 000s of them...

Could we a) ditch video support, or b) implement some kind of short name treatment on URLs?

**Comment by george08** [comment]
Will relate to Heroku system too, as that generates the tag contents.

**Comment by george08** [comment]
@amcewen about to order a bunch of stickers - which ones should we get?

**Comment by amcewen** [comment]
We can, if need be, both ditch video and do shortcodes.  I don't think the brain will care about shortcodes if we do that, but I'll remove the video support for now and we can do the shortcodes if we run out of room in future.

So let's go with the NTAG213s

**Comment by george08** [comment]
@amcewen i've just ordered 2,000 stickers! hoping we can get to this soon!

**Comment by george08** [comment]
We're now working backwards from a deadline for Smithsonian delivery: April 16.

**Comment by amcewen** [comment]
Should be able to.  I'm going to fold in the configure-wifi support first (it's been developed in a separate branch so far, so will merge it onto master) and then get on this
