### ISSUE TITLE
We're on a new Wifi network... therefore:

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#45]
Either, 
1) We update the blue and pink brains with the new Wifi image, or
2) You hard-code the new wifi network into an update and we put on blue or pink brains.

(1) is not possible because the blue and pink brains have 8GB SD cards... see #46.

We're a bit stuck on lots of fronts until this is resolved (e.g. can't make new sets/objects because blank objects trigger the Wifi config bits on Yellow.)

**Comment by amcewen** [comment]
A new image with the old card details in will be best (otherwise you'll have the same "can't use blank objects" problem on the blue/pink brains.  I'll build one for you.

**Comment by george08** [comment]
Hiya - what's the status on this, please?

**Comment by amcewen** [comment]
New image was built and delivered on 24th Jan.  There'll be another one along soon with the configurable WiFi stuff and the new box provisioning stuff, but that needs some testing (and _I think_ some more work from the Heart side of things)
