### ISSUE TITLE
Photograph complete exploded view of Brain/Skull version 1.0

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#47]
I think this would be excellent documentation, not only for us to capture where we're at now, but also possibly prep/background materials for Make Your Own down the line.

We could blog the crap out of it, and make cool GIFs for the kidz.

**Comment by CharlieMiab** [comment]
Will get cracking on this once we have received all the ordered parts.

**Comment by george08** [comment]
Missed our chance on this :)
