### ISSUE TITLE
Need a way to control volume

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#5]
Particularly on the laser cut box from Dec 8.

**Comment by amcewen** [comment]
Just a quick update - haven't been able to create a fix for this yet as the spare (super cheap) microSD cards are all dodgy and won't work in the R.Pi.

Have ordered some better (I hope) replacements, so will get it sorted once they arrive (in the new year if not next week)

**Comment by amcewen** [comment]
Okay, have got a working version now, and have worked up a not-perfect-but-hopefully-good-enough fix.

If you go to the control panel for the brain you want to change the volume for - the http://brain-1.local:1880/ URL for example - then you can add this to give you a functional volume control...

Copy the following chunk of JSON to your clipboard:

[{"id":"b69a4894.a22d5","type":"inject","name":"Full (400)","topic":"","payload":"400","payloadType":"string","repeat":"","crontab":"","once":false,"x":154.44444444444443,"y":541.1111111111111,"z":"8c018666.713f4","wires":[["4a5bc959.0e1758"]]},{"id":"3979d3a8.6b0134","type":"inject","name":"Off (-10239)","topic":"","payload":"-10239","payloadType":"string","repeat":"","crontab":"","once":false,"x":146.66668701171875,"y":586.6666870117188,"z":"8c018666.713f4","wires":[["4a5bc959.0e1758"]]},{"id":"3f4a2166.0600c6","type":"inject","name":"","topic":"","payload":"-500","payloadType":"string","repeat":"","crontab":"","once":false,"x":154.44444444444443,"y":637.7777777777777,"z":"8c018666.713f4","wires":[["4a5bc959.0e1758"]]},{"id":"4a5bc959.0e1758","type":"exec","command":"amixer cset numid=1 -- ","addpay":true,"append":"","useSpawn":"","name":"set volume","x":361.1111111111111,"y":580,"z":"8c018666.713f4","wires":[[],[],[]]}]

Then click the burger menu in the top right corner of the control panel, choose Import, then Clipboard.  Paste the JSON into the Import Nodes dialog box and click OK.

That will give you four new nodes - one labelled "set volume" and three others with different volume options.  Clicking the "Deploy" button in the top right corner will save those nodes so you can use them (and so they'll be there next time you boot up too)

Clicking on the little rounded-corner square button to the left of one of the options will set the volume to that level.  If you want a different volume level then double-click on one of them, type a different number into the payload (below the drop-down that says "string"), and then "Ok" and "Deploy".  The volume level can be anything between -10239 and 400 (such easy-to-remember values, no?!?)

I think you'll need to set it each time you boot, sadly, but I can work on something better next time I'm down.

**Comment by amcewen** [comment]
We've now got hardware volume controls on the built-in amplifier
