### ISSUE TITLE
Recognise an object on the box at boot time

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#50]
People often place an object onto the box during the boot process.  We should spot that and play the correct content as soon as we've booted up.

**Comment by amcewen** [comment]
This was fixed in the same commit as the fix for #44 - https://github.com/museuminabox/brain/commit/cd78b5850a8916a6fffd1a6ad459a3b0a0275ae6.  

There is a tiny bit of overlap between the "Ok.  Let's go!" audio and the start of the audio for the tag, but having it delay until the ready audio has played is non-trivial, so I'm going to leave it as is for a while and we can see how much of a problem it is.

**Comment by amcewen** [comment]
Hmm,when there isn't an object on the box, there's a race condition between the "OK, ready to go" audio playing and the "kill all the audio" because there isn't an object present, which means you can either get no "OK, ready to go" at all, or just the "OK"

**Comment by george08** [comment]
If the Gill figure is on the Box before the "OK, ready to go" is played, you could just play the "A ha! So you've worked it out."

**Comment by amcewen** [comment]
I can't get Node RED to detect whether there's an object present or not in order to decide *which* to play (the trying to read a tag will fail if there's no object there, but that just stops execution of that rather than letting me decide to play something different), but I can stop it from playing both of them at the same time.

So, it now plays the "OK, ready to go!" audio and then plays any object audio, if there's an object on the box.

**Comment by george08** [comment]
Cool - did you set a small delay between the two?
