### ISSUE TITLE
Know/detect whether Gill figure is on the reader once the Box is ready

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#51]
About 99% of the time, when we ask people to open up the box and turn it on themselves, they put Gill on the box as soon as they've plugged it in.

Then, when she finally says she's ready, they're not sure what to do. Some take her off and put her back again, but others are stumped.

Wondering if it's possible to either:
a) Make bootup happen in a second ;)
b) Have Gill say a different script if she's already in position once the Box is ready?

**Comment by amcewen** [comment]
With the changes in #50 (which aren't in a release yet, so only I've seen them) you'd get Gillian saying she's ready and then immediately (and there might be a tiny overlap in them, unless there is/we add a tiny pause at the start of the audio for the Gillian object's audio) start the Gillian object audio.

Having the objects play different audio at different times feels like a post-v1 feature to me, so if the fix to #50 will suffice for v1 then I'd suggest filing this under a "future version" label (that we should create to collect such feature requests)?

**Comment by george08** [comment]
See #50
