### ISSUE TITLE
Set per-box passwords

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#54]
The boxes currently all end up with the same password.  That's useful for letting us get into them to tweak things, but not very secure.

We should get the setup process to generate a unique password for that box.  I don't think we need to know what the password is, as we can provision the boxes with SSH certificates (and currently do for the initial Ansible provisioning process) to allow us to log in without needing a password.

When I'm next in London I'll sort out setting up certificates for @george08 and @CharlieMiab, and store the public certs we can then provision.  In addition, we should save a "MiaB central" set of SSH certs "somewhere safe" so that even after people have upgraded their computers we'll still be able (with a bit of hassle) set a computer up which can log in.

**Comment by amcewen** [comment]
Pondering implementing this now, it's going to be tricky with our current provisioning system, so for now we're going with one per version, rather than one per box.

**Comment by george08** [comment]
Can we close this then?

**Comment by amcewen** [comment]
Might as well, can always open a new one once there's a more obvious solution.
