### ISSUE TITLE
Consider dropping one of the progress LEDs

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#58]
For the v1 hardware, we end up with a wiring loom that has 9 wires to go to the progress PCB and two wires to go to the power connector on the amp.  If we had one fewer LED then we'd only need 8 wires for the progress board and so only 10 wires would be needed in the loom.

That would result in no wires left over and would mean we'd keep the same colour scheme through all of the boards.

**Comment by george08** [comment]
I'm guessing this didn't make it into the PCBs we just ordered :)

**Comment by amcewen** [comment]
It didn't.  Feels like there's likely to be bigger PCB changes for the next big round of building we'd do, so I'm going to close this but tag in #86 so it might get considered then (although a lot of that will be about removing wires completely so would hopefully make this a non-issue...)
