### ISSUE TITLE
Reimplement code in pure NodeJS

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#62]
We're reaching the limits of what's easily achievable with the Node-RED implementation.  It would be better to rework all of the code in NodeJS.

**Comment by amcewen** [comment]
This is a slightly longer-term issue, and so something to consider post-commission.

**Comment by george08** [comment]
What are you thinking for this round - a rewrite now?

**Comment by amcewen** [comment]
Done and in the new repo.
