### ISSUE TITLE
Help sync/debug Jewish Museum brain?

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#66]
Hi Adrian,

We're supposed to be delivering the brain upgrade this week, and on Friday, it seemed like the brain (old Raspberry Pi, new software) was glitching a bit, by not always saying "One moment please, I'm just warming up."

Can you help debug tomorrow (Tuesday), please? (I thought I recalled you saying it's a software issue?)

**Comment by amcewen** [comment]
New tweak to the startup ordering in the `img` file I shared earlier.  If that doesn't help then I can see what else we can investigate.
