### ISSUE TITLE
Show box ID etc on box.local/setup if known

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#71]
If the Box is already in the system, show its settings on /setup.

**Comment by george08** [comment]
(Charlie just recreated the Jewish Museum box inadvertently, and now we have two - id=53 and id=70.)

Don't know the best thing to do here - or how to make a new box be an old box :)

**Comment by amcewen** [comment]
The new `/upgrade` path also shows the ID of the box if it's got one (and ditto on `/setup`), so the next release should sort this out

**Comment by george08** [comment]
Coolio... where are you controlling those HTML pages? Maybe I can help a bit with the language/layout...?

**Comment by amcewen** [comment]
They're written as html in `http://box.local:1880/`.  I'll point you at them once the new image is done and then can easily fold in any changes

**Comment by george08** [comment]
Ok. If they're .txt or .html somewhere in GitHub at some point I can go to town :)

...
George Oates
Director 
gfns.uk
