### ISSUE TITLE
Add a Museum in a Box logo to the wifi password page

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#72]
Seeing resin.io there might be disconcerting. (So, remove that and replace with the MB logo.)

**Comment by amcewen** [comment]
Done.  The whole UI is now in [miab/wifi-ui](https://github.com/museuminabox/brain/tree/master/miab/wifi-ui) if you want to do any more fettling of it.

**Comment by george08** [comment]
I'll take a crack at some of that copy soon.

**Comment by amcewen** [comment]
Do we want to make any more changes to this, or is it okay now?

**Comment by george08** [comment]
We can close for now. Ta.
