### ISSUE TITLE
Upgrade UI on box.local - no boxes show up in the list

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#74]
Just downloaded the 0411 image, and this is what I see on /upgrade:

![image](https://user-images.githubusercontent.com/354542/38680154-84933460-3e5d-11e8-80e1-35862f1bbeb1.png)

But, I entered the ID (69), and it took me to /prints with the correct list of stuff.

**Comment by amcewen** [comment]
Were you logged into `heart` on the computer/browser you were using for that?  I'm pretty sure that's why you're getting a blank screen rather than the list.

I'm not sure why you don't get a login screen when it's in the iframe, though...

**Comment by george08** [comment]
Hi. I'm fairly sure I was logged in, just because I was flipping back and forth around heart at the time. Maybe it's a safari thing?

...
George Oates
Director 
gfns.uk

**Comment by george08** [comment]
Need to have a proper think about how to interface with Box UI from /heart, and what we can transfer to /heart system, if anything.

**Comment by amcewen** [comment]
We don't have the `/upgrade` page any more...
