### ISSUE TITLE
Record proper audio for Box/Update/WiFi config

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#75]
The configuring the WiFi on the box has three audio files.  We should record proper audio for them rather than off-the-cuff test recordings from me :-)

 * `configure-wifi.wav` Initial instructions on what to do when we launch the WiFi config tool
 * `WiFi_works.wav` Played once you've successfully connected to the WiFi
 * `WiFi_failed.wav` Played if you didn't get the WiFi configured (either it failed, or it timed out - currently after 2 minutes)

**Comment by amcewen** [comment]
Ditto for the updates audio from #55:
 * `updates-check.wav` Let the user know we're looking for updates
 * `updates-ok.wav` Either the update was successfully applied or there wasn't one to apply
 * `updates-failed.wav` Something went wrong with the update

**Comment by george08** [comment]
Scripts are here: https://github.com/museuminabox/brain/wiki/Box-Audio-Scripts

Have suggested a few new ones, per #93.

**Comment by george08** [comment]
Just found https://oldstreetstudios.com around the corner, and they're super cheap (for London). Hoping to arrange for next week.

**Comment by george08** [comment]
Here's the audio - per the script doc: https://github.com/museuminabox/brain/wiki/Box-Audio-Scripts
https://www.dropbox.com/sh/txw4ylo845t4mqg/AADITM_JsduWgvPXbaiZJwpua?dl=0

**Comment by george08** [comment]
This is so done.
