### ISSUE TITLE
Make box.local:1880 a more user-friendly page

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#83]
We should move the admin details onto a `/admin` endpoint (or similar), protected with a username/password and then make `/` return a holding page of some form - something that we can point users to if they need to check that their device is online.

**Comment by george08** [comment]
It would be good to talk over what's possible in terms of design/user-friendliness in person.

**Comment by amcewen** [comment]
Yes, feels like this ties in with #93 too

**Comment by amcewen** [comment]
Annoyingly if we change the port that the WiFi config server sits on to anything other than 80 then Android phones (at least, I didn't test anything else) won't be able to connect to it to set up the WiFi.  So we'll have to stay on port 1880 (at least until there's a way to integrate the two servers)
