### ISSUE TITLE
Start-up audio is temperamental/inconsistent 

### ISSUE THREAD

**Issue by CharlieMiab** [museuminabox/brain#87]
Boxes don't always play both 'one moment please I'm just warming up' and 'ok, ready to go' notifications on start-up. Sometimes only the first notification plays, sometimes only the second and sometimes both with no obvious reasoning for why.

**Comment by george08** [comment]
Need to be able to replicate this.

**Comment by amcewen** [comment]
Haven't seen it miss the "ok, ready to go" audio, but the "one moment please" being missed happens fairly often

**Comment by CharlieMiab** [comment]
Yes we're still experiencing it with the 80 boxes in HQ and it's the "one moment please" audio that is missed not the "Ok, ready to go".

**Comment by amcewen** [comment]
Have had 20 boots (a combination of warm [restarting in software] and cold [pulling power and starting from scratch]) without any problems in it, so fingers crossed the timing is now sorted for the soundcard to always be ready when we play the "one moment please" audio.
