### ISSUE TITLE
Stubborn writing tag 'Try again' notification requires box restart

### ISSUE THREAD

**Issue by CharlieMiab** [museuminabox/brain#88]
When writing tags often a tag won't work when clicking 'write' and the 'Try again' notification will come up immediately. Multiple clicks don't solve it and neither does removing and replacing the object on the box. The only way around this is to restart the box and refresh box.local:1880/prints. Normally fixes the problem but of course slows down the process of writing a new collection.

**Comment by george08** [comment]
See #93
