### ISSUE TITLE
Switch to the RC522 RFID reader

### ISSUE THREAD

**Issue by amcewen** [museuminabox/brain#92]
Are any of the other RFID/NFC readers better/cheaper?

**Comment by amcewen** [comment]
I tried a bunch of the PN532-based readers:
 * [Rectangular blue one](https://www.ebay.co.uk/itm/PN532-NFC-Precise-RFID-IC-Card-Reader-Module-Raspberry-For-Arduino-Blue-Inducing-/392102348483?nordt=true&orig_cvip=true&rt=nc&_trksid=p2047675.m43663.l10137)
 * [Square red one](https://www.ebay.co.uk/itm/DIY-Kit-PN532-NFC-RFID-Module-Reader-Writer-For-Arduino-Android-Phone-Module/392107867001?_trkparms=aid%3D777003%26algo%3DDISCL.MBE%26ao%3D2%26asc%3D52945%26meid%3Ddbe8a1a24887482087268be37c458894%26pid%3D100012%26rk%3D5%26rkt%3D12%26sd%3D392102348483%26itm%3D392107867001&_trksid=p2047675.c100012.m1985)
 * [Adafruit NFC reader](https://www.adafruit.com/product/789)

I got all of them working over i2c with an ESP32, and also with an Arduino Uno, using the Adafruit library.

However, the blue and red ones were intermittent in which tags they could read.  Nothing specific to the type of tag, but only about half of the tags I tried (MiFare Classic 1K, NTAG203, NTAG213, NTAG216) worked :-(

The Adafruit reader could read all the tags just fine, but is bigger than the SL030 and more expensive.

I've just got one last reader to try - an RC522.  They're ~£4 each.

**Comment by amcewen** [comment]
The RC522 seems to work okay - it seems to read all the tags okay (all the ones I've got knocking around anyway).

Looking on Aliexpress, they're available for ~$1.50 each ([for example](https://www.aliexpress.com/item/Free-Shipping-13-56MHz-I2C-SPI-RFID-Module-For-Arduino-MF-RC522-RC-522-Reader-Writer/32803648297.html?ws_ab_test=searchweb0_0,searchweb201602_1_10065_10130_10068_318_10547_10548_10696_10192_10190_10084_10083_10618_452_10307_10820_532_10821_10301_10303_204_10059_10884_10887_100031_10103,searchweb201603_2,ppcSwitch_0&algo_expid=dbdcf74b-3c9b-4488-9a67-ec0b12cd6da8-4&algo_pvid=dbdcf74b-3c9b-4488-9a67-ec0b12cd6da8&transAbTest=ae803_4&priceBeautifyAB=0)).  

The only downside to them seems to be that they don't have an LED to indicate when they've detected a card, so there's not that additional bit of feedback to let you know you've got the tag in the right place.

**Comment by george08** [comment]
Should we close this and make a new Issue about any code rewriting that's required @amcewen?

**Comment by amcewen** [comment]
Don't think it makes a lot of difference.  The rename makes it more obvious that it could also collect the code changes here too - and that's the remaining bit of work required now.

**Comment by amcewen** [comment]
Code is done for this, and integrated into the rest of the brain.  Needs plenty more testing but we can open new bugs (or reopen this) if we find any problems.
