### ISSUE TITLE
Which wires to we attach to the Aux Out?

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#97]
Hi @amcewen - we've started the prep for box making, and have a question about Step 4 on this plan:

https://github.com/museuminabox/brain/wiki/Getting-components-prepared

We've trimmed and are stripping the double-ended Aux jacks, but there are four wires inside, not three like last time: white, red, green and black. 

In the previous box, the Aux Out has green, white, and red soldered to it, but we weren't sure if that's transferable, since we now have an extra black wire...

**Comment by amcewen** [comment]
RTFM ;-)  https://github.com/museuminabox/brain/blob/master/Physical/README.md#wiring-the-audio-circuit has more detailed instructions about the wiring (and the previous box will have a blue or black wire that's not connected, but it'll have been snipped off near the insulation as it's not needed).

However, you're right that the old colour-coding won't necessarily match the new colour-coding.  The best way to check would be with a multimeter, but I don't think you've got one?  As a fall-back you could create a circuit through the wire to check that the right bit is connected, using a Pi, a few jumper wires, and an assembled Boot Progress board:
  1. Connect a wire to one of the +3V3 pins on a Pi (see [this wiring diagram](http://elinux.org/RPi_Low-level_peripherals#Model_A.2B.2C_B.2B_and_B2))
  1. Connect another wire from one of the GND pins on the Pi to pin 9 on the Boot Progress PCB (see [the pin-out for that here](https://github.com/museuminabox/brain/blob/master/Physical/README.md#bootprogressboard))
  1. Connect a wire to pin 8 on the Boot Progress PCB
  1. You'll have two not-connected wire ends from the other ends of the wires in step 1 and 3.  Hold one of the wires against one of the bits of the 3.5mm jack plug that you want to test, and then hold the other wire against one of the coloured wires of the aux cable.  If the LED on the Boot Progress PCB lights up then that bit of the 3.5mm jack is connected to the coloured wire you chose.  If it doesn't work through the rest of the coloured wires until you find the one that's connected.
  1. Note down the connection you've just found
  1. Repeat from step 4 for the next bit of the 3.5mm jack plug, until you've worked out which is which for all of them.
  1. You'll now know which colour is which for the tip, ring 1 and ring 2 connections listed in https://github.com/museuminabox/brain/blob/master/Physical/README.md#wiring-the-audio-circuit

**Comment by amcewen** [comment]
For bonus points, update https://github.com/museuminabox/brain/blob/master/Physical/README.md#wiring-the-audio-circuit to document the latest wiring colour-coding so we don't have to run through the process again next time we're building boxes :-D

**Comment by george08** [comment]
@CharlieMiab want to take a crack at this?

**Comment by CharlieMiab** [comment]
@george08 @amcewen I can give it a damn good try!

**Comment by george08** [comment]
Cables are all connected now.
