### ISSUE TITLE
Do a design rev on the Progress Bar PCB to include human-readable labels for the various sections

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#98]
I like the way Tom added labels (and version number etc) to the amp board. Hoping for similar on Progress Bar!

**Comment by george08** [comment]
- 1x orange dot
- 6x yellow dots
- 1 big mama LED

- single resistor
- resistor array
- 9x right angle header

**Comment by amcewen** [comment]
We're not planning another rev of this progress board now.
