### ISSUE TITLE
Add links/nav to /setup

### ISSUE THREAD

**Issue by george08** [museuminabox/brain#99]
Can we please add the nav bar from the /prints page to other pages on box.local (especially if we're going to be showing this to MYOMB pilots).

![image](https://user-images.githubusercontent.com/354542/49865598-4a4e5180-fdfd-11e8-82e3-d8835fd6d9e8.png)

http://box.local:1880/upgrade
http://box.local:1880/setup

**Comment by george08** [comment]
@amcewen I'm happy to do this, if you can please point me at wherever the html/markup is for those pages... had a hunt in the repo, but couldn't track 'em down!

**Comment by amcewen** [comment]
This was done, and we no longer have `/setup` or `/upgrade`, so we can close it.
